name: Deploy to K8s

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Development
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEVELOPMENT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEVELOPMENT_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: samplemedit
        IMAGE_TAG: tematres-${{ github.ref_name }}-${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  kustomize:
    name: Clone Apps Repository
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone Kubernetes Apps
        uses: actions/checkout@master
        with:
          repository: Samplemed/kubernetes-apps
          path: kubernetes-apps
          token: ${{ secrets.GH_TOKEN }}
      - name: Initialize Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v5.0.0      
      - name: Run Kustomize
        run: |
          cd kubernetes-apps/apps/tematres/overlays/${{ github.ref_name }}/
          kustomize edit set image app=${{ secrets.DEVELOPMENT_ECR_REPOSITORY }}:tematres-${{ github.ref_name }}-${{ github.sha }}
          kustomize edit set image phpcli=${{ secrets.DEVELOPMENT_ECR_REPOSITORY }}:tematres-${{ github.ref_name }}-${{ github.sha }}

      - name: Commit Changes
        run: |
          cd kubernetes-apps/apps/tematres/
          git config --global user.email "devops@samplemed.com.br"
          git config --global user.name "Samplemed IT"
          git commit -am "chore(kustomize): change tematres api image tag ${{ github.sha }}"  
          GH_TOKEN=$GH_TOKEN git push